### PR TITLE
switch to socket2

### LINKED ISSUE #1: Invalid assumption of SocketAddrV{4,6} layout
This code assumes that Rust's `std::net::{SocketAddrV4, SocketAddrV6}` are layout compatible with `sockaddr`:

https://github.com/smol-rs/nb-connect/blob/f706c11d75fbdae0ac7fe633f3bf7390bd4f79c5/src/lib.rs#L61-L84

This is not guaranteed by the standard library, see https://github.com/rust-lang/rust/pull/78802 for more details.

### PR DESCRIPTION
**Pull request by Keruspe**
Now that socket2 is getting the attention it needed, this simplifies a lot the code, which just becomes a thin wrapper.

This also fixes #1 as a side-effect.

### CODE REVIEW

**Comment by Keruspe** [comment]
(I actually wanted to try this out to fix #1 in the first place. I'm not sure if we want to do that, but since socket2 might eventually become the std impl, I though this could make sense?)

This will oviously have to wait for 0.4 to actually be released

**Comment by taiki-e** [comment]
This will be blocked until the 0.4 release of socket2, but I'm in favor of this. (It is more actively maintained/developed than nb-connect and has been checked/tested on various platforms.)

(The socket2 maintainer previously said that [socket2 is not ready for production use](https://github.com/tokio-rs/mio/issues/1366#issuecomment-706044501), but that will probably improve in 0.4.)

EDIT: marked this PR as draft as this is blocked until the 0.4 release of socket2.

**Comment by Keruspe** [comment]
@taiki-e I guess downgrading to 0.3 could unblock this? Then we'll just be able to revert this to switch to 0.4 once released

**Comment by JayceFayne** [comment]
Looking at this pull it seems like it defeats the purpose of why this crate was created in the first place.
`nb-connect` was created to specifically not depend on `socket2` see [this issue](https://github.com/smol-rs/async-io/issues/27#issuecomment-691225149) and [this pull](https://github.com/smol-rs/async-io/pull/28) :confused: 

Don't get me wrong, I understand why this pull was proposed but if we introduce `socket2` as dependency to `nb-connect` we can replace `nb-connect` with `socket2` in `async-io` directly instead of relying on `nb-connect`

**Comment by taiki-e** [comment]
@JayceFayne Thanks for the info. I didn't know why this crate was created.

When I consider the following things, I think that it is better to depend on socket2 than maintain the partial fork of the old socket2 that contains unsafe code. (Even if socket2 contains a lot of unsafe code.)
- socket2 is being actively developed as part of the rust-lang organization. Soundness issues like #1 are fixed fast enough by maintainers and the community.
- Maintenance status of the smol project is ["passively-maintained"](https://doc.rust-lang.org/cargo/reference/manifest.html#the-badges-section), and there is no maintainer with bandwidth to track socket2's changes.
- socket2 is not a heavy dependency.

@smol-rs/admins What do you think?

> we can replace `nb-connect` with `socket2` in `async-io` directly instead of relying on `nb-connect`

It makes sense. After merging this PR, I would like to replace the use of nb-connect with a direct dependency on socket2.

**Comment by zeenix** [comment]
> > ``
> 
> It makes sense. After merging this PR, I would like to replace the use of nb-connect with a direct dependency on socket2.

And perhaps it'd make sense to mark nb-connect as deprecated in favour of socket2?

**Comment by taiki-e** [comment]
> And perhaps it'd make sense to mark nb-connect as deprecated in favour of socket2?

I thought a simple wrapper crate might be useful because we sometimes have to write [a lot of cfg](https://github.com/smol-rs/nb-connect/pull/5/files#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R45-R54) when using socket2, but since there are [very few direct users of this crate](https://crates.io/crates/nb-connect/reverse_dependencies), deprecation seems to make sense.

**Pull request merged**
